### ISSUE TITLE
Xamarin.Forms.Proxy is not compatible with Xamarin.Forms 3.1.0.697729

### ISSUE THREAD

**Issue by TerryDieckmann** [Keboo/Xamarin.Forms.Proxy#2]
Inaccessible properties and changed methods / overloads in Xamarin.Forms **3.1.0.697729** causes Xamarin.Forms.Proxy not to build anymore.

Will Xamarin.Forms.Proxy be updated in the near future?

**Comment by Keboo** [comment]
Updated to Xamarin.Forms 3.1.0.697729. Check out the latest code and let me know if you are still having problems.
