### ISSUE TITLE
Support for Xamarin.Form 4.0.0.497661

### ISSUE THREAD

**Issue by npagare** [Keboo/Xamarin.Forms.Proxy#3]
Hi @Keboo,

Thank you for putting this MultiBinding class. 
Will you be release a version that support Xamarin.Forms 4.0+ ?

I am running into following error, when I tried compiling against XF 4.0.0.497661 -

1>Build FAILED.
1>
1>MultiBinding.cs(125,43,125,52): error CS0411: The type arguments for method 'BindableObject.GetValues<T>(BindableProperty[])' cannot be inferred from the usage. Try specifying the type arguments explicitly.
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:19.26
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Keboo** [comment]
Hi @IoTFier 
I have updated the project to XF 4.0. Let me know if there are any issues.

**Comment by npagare** [comment]
Thank you @Keboo
