### ISSUE TITLE
Values passed inside Convert method are null .

### ISSUE THREAD

**Issue by alkharashiam** [Keboo/Xamarin.Forms.Proxy#4]
Hi , 
So I am using MultiBinding with the FirstNotNullConverter example . everything works But when I try to change the code inside Convert method in FirstNotNullConverter like this : 

return values[0]/values[1];
(im trying to divide the first binding with the second and return the result )
it gives me a null exception error and when I debug my code i see both values[0] and values[1] are null

any suggestions ?

**Comment by Keboo** [comment]
Hi @alkharashiam this is somewhat expected. 
The converter is going to get invoked when the binding is initially applied. In most cases the initial values in the array, are likely going to be null. In your value converter you should check for null values and only perform your logic when you have valid values.

I uploaded an example repo that also has a `ColorConverter` that demonstrates this same type of logic.

**Comment by alkharashiam** [comment]
@Keboo  I just test your colorConverter and implemented my own .. works like a charm 
Thanks

**Comment by Keboo** [comment]
@alkharashiam Glad it is working. Happy coding.
